#!/usr/bin/env bash
# task 1
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  dagem-alx-frontend
        bind *:80
        mode http
        default_backend dagem-alx-backend
backend dagem-alx-backend
        balance roundrobin
        server 335-web-01 35.196.185.163:80 check
        server 335-web-02 34.75.166.190:80 check
"
 echo "$server_config" >> /etc/haproxy/haproxy.cfg

 # enable haproxy to be started by init script

 echo "ENABLED=1" >> /etc/default/haproxy

 sudo service haproxy restart
